// 自動生成ファイル — 編集禁止。crm/scripts/sync.py が生成する。
const customersAuto = [
  { id: "yuta", name: "雄太さん", real: "雄太", priority: "P0", statusKey: "waiting", status: "EDM軸決定・ジェヘナドロップ課題提示済み・1週間進捗待ち", plan: "無料", planPrice: "¥0", nextAction: "雄太さんから1週間以内の進捗報告 or 質問を待つ", nextDue: "2026-05-15頃（1週間後）にこちらから確認", contact: "LINE", daw: "Studio One Professional", genre: "EDM（軸決定）／ エレクトロスウィング（後で）", file: "customers/yuta.md" },
  { id: "yasu", name: "やすさん", real: "保浦康晴", priority: "P0", statusKey: "active", status: "新ロードマップPROコース購入済み・STEP6完了・STEP7着手前", plan: "新ロードマップPROコース + 3ヶ月サポート", planPrice: "¥19800", nextAction: "STEP7の取り組み・進捗報告 or 質問待ち", nextDue: "STEP7進捗報告待ち", contact: "LINE", daw: "Ableton Live", genre: "Melodic Techno（Anymaが好き）", file: "customers/yasu.md" },
  { id: "minoru", name: "Minoruさん", real: "Y K.", priority: "P0", statusKey: "waiting", status: "初期納品送付済み・修正フィードバック待ち", plan: "スタンダードコース", planPrice: "¥9800", nextAction: "Minoruさんからのフィードバック待ち（修正残り2回・指導期間〜5/17）", nextDue: "フィードバック待ち", contact: "Discord / メール（PCメイン）", daw: "Cubase", genre: "ジブリ系×スイング×ダンス（四つ打ち）×昭和歌謡×EDM", file: "customers/minoru.md" },
  { id: "daiki", name: "DAIKIさん", real: "DAn", priority: "P0", statusKey: "paid", status: "成約済み（入金確認待ち）", plan: "新ロードマップPROコース + 3ヶ月サポート + ビデオ面談（特別アドオン）", planPrice: "¥29600", nextAction: "新LP案内メッセージへのDAnさんからの反応待ち + Stripe入金確認 + 5/8以降のセッション日程提案待ち", nextDue: "反応待ち", contact: "—", daw: "未開始（機材は揃っている）", genre: "Techno / Tech House", file: "customers/daiki.md" },
  { id: "shoryu", name: "翔琉さん", real: "翔琉", priority: "P0", statusKey: "waiting", status: "ジャンル受領後・ミックス相談への第2回返答送付済み・反応待ち", plan: "無料", planPrice: "¥0", nextAction: "翔琉さんからの反応を待つ（音源依頼を承諾するか／JPOPロック専門を探すか／自力で進めるか）", nextDue: "反応待ち", contact: "LINE", daw: "不明（要確認・本人活動は耳コピ中心）", genre: "JPOPロック / ボカロP系譜（ヨルシカ・n-buna 系統）", file: "customers/shoryu.md" },
  { id: "tatsuyan", name: "TatsuyaNさん", real: "", priority: "P0", statusKey: "waiting", status: "第一回FB送付済み・反応待ち", plan: "DTMロードマップ（有料note）", planPrice: "—", nextAction: "ベース打ち込みタイミング修正後の音源待ち / フィルインサンプル送付待ち", nextDue: "返信待ち", contact: "LINE", daw: "Ableton Live 12", genre: "歌モノ・メロディが映える曲（ビートジャンル未定）", file: "customers/tatsuyan.md" },
  { id: "nob", name: "NOBさん", real: "NOB", priority: "P2", statusKey: "active", status: "旧ロードマップ1.0（有料note版）・STEP7進行中・延長サポート中・応援者", plan: "旧ロードマップ1.0（有料note版・¥9,800）", planPrice: "¥9800", nextAction: "", nextDue: "", contact: "LINE", daw: "Ableton Live", genre: "Tech House / House", file: "customers/nob.md" },
  { id: "takamatsu", name: "高松さん", real: "高松泰樹", priority: "P2", statusKey: "active", status: "旧ロードマップ1.0（有料note版）・**STEP1〜STEP10 完走済み**・人生転換ストーリー顧客", plan: "旧ロードマップ1.0（有料note版・¥9,800）", planPrice: "¥9800", nextAction: "", nextDue: "", contact: "LINE", daw: "FL Studio", genre: "同人音楽風（bermei.inazawa方向）／ダンスミュージック寄りの感動系", file: "customers/takamatsu.md" },
  { id: "urano", name: "うさださん（上野麻弥さん）", real: "上野麻弥", priority: "P2", statusKey: "active", status: "旧ロードマップ1.0（有料note版）+ ラボ購入済み・STEP3進行中・延長サポート中", plan: "旧ロードマップ1.0（有料note版・¥9,800）+ トリケラテクノ・ラボ購入済み", planPrice: "¥9800", nextAction: "", nextDue: "", contact: "LINE", daw: "Bitwig Studio", genre: "ハウス・テックハウス・テクノ（特に Minimal / Peak Time Driving 系）", file: "customers/urano.md" },
  { id: "natsuki", name: "なつきさん", real: "長野大樹", priority: "P2", statusKey: "free", status: "無料サポート中（有料化タイミング）", plan: "無料", planPrice: "—", nextAction: "「1曲完成おめでとう＋チャンネル活動の確認」の返信を待ち", nextDue: "今週中", contact: "LINE", daw: "GarageBand", genre: "Frenchcore / Speedcore", file: "customers/natsuki.md" },
  { id: "atsuki", name: "ATSUKIさん", real: "ATSUKI", priority: "P2", statusKey: "active", status: "Break+LUFS FB完成版あり・送信保留（向こうから欲しがってから送る方針）", plan: "無料", planPrice: "¥0", nextAction: "ATSUKIさんから音源 or 質問が来たら、保留中の Break+LUFS FB を送付", nextDue: "反応待ち（こちらから動かない）", contact: "LINE", daw: "FL Studio", genre: "Progressive House", file: "customers/atsuki.md" },
  { id: "hirokazoo", name: "hirokazooさん", real: "Dさん", priority: "P2", statusKey: "free", status: "無料相談中（段階的FB継続）", plan: "無料", planPrice: "—", nextAction: "キックニンジャ改善結果が来たら次のFB", nextDue: "返信待ち", contact: "LINE", daw: "Bitwig Studio", genre: "PsyTrance（Full On Trance）", file: "customers/hirokazoo.md" }
];